name          'opentable-puppetdb_rundeck'
version       '0.1.0'
source        'git://github.com/opentable/puppet-puppetdb_rundeck.git'
author        'opentable'
license       'MIT'
summary       'Module that installs and manages the puppetdb_rundeck gem'
description   'Module that installs and manages the puppetdb_rundeck gem to provide a puppetdb resource for rundeck'
project_page  'https://github.com/opentable/puppet-puppetdb_rundeck'
dependency    'puppetlabs/stdlib'
